language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
env:
  - DJANGO=Django==1.9.4

# command to install dependencies
install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -q https://github.com/praekelt/django-setuptest/archive/f4eacb4a929cdcc853a5c053c282dada5bdedc99.tar.gz

# command to run tests
script:
  - python setup.py test
