# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 18:40
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_kudago_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='event',
        ),
        migrations.AddField(
            model_name='schedule',
            name='event',
            field=models.ManyToManyField(blank=True, to='test_kudago_import.Event'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='place',
        ),
        migrations.AddField(
            model_name='schedule',
            name='place',
            field=models.ManyToManyField(blank=True, to='test_kudago_import.Place'),
        ),
    ]
